'use strict';const crypto=require('crypto');
const states={draft:['evidence_review','withdrawn'],evidence_review:['approval_pending','changes_requested','withdrawn'],changes_requested:['evidence_review','withdrawn'],approval_pending:['approved','changes_requested','rejected'],approved:['released','superseded'],released:['superseded','withdrawn'],rejected:[],superseded:[],withdrawn:[]};
const grants={author:['draft:evidence_review','draft:withdrawn','changes_requested:evidence_review','changes_requested:withdrawn'],reviewer:['evidence_review:approval_pending','evidence_review:changes_requested'],approver:['approval_pending:approved','approval_pending:changes_requested','approval_pending:rejected','approved:released'],records_manager:['released:superseded','approved:superseded','released:withdrawn'],admin:['*']};
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v)}const digest=v=>crypto.createHash('sha256').update(canonical(v)).digest('hex');
function ingest(source){for(const k of ['sourceId','sourceUri','publisher','jurisdiction','effectiveAt','retrievedAt','version','content'])if(!source[k])throw new Error(`${k} required`);if(!/^https:\/\//.test(source.sourceUri))throw new Error('authoritative HTTPS source URI required');const effective=Date.parse(source.effectiveAt),retrieved=Date.parse(source.retrievedAt);if(!Number.isFinite(effective)||!Number.isFinite(retrieved))throw new Error('valid source dates required');return{...source,contentDigest:digest(source.content),provenanceDigest:digest({sourceId:source.sourceId,sourceUri:source.sourceUri,publisher:source.publisher,jurisdiction:source.jurisdiction,effectiveAt:source.effectiveAt,version:source.version})}}
function detectChange(previous,incoming){const normalized=ingest(incoming);if(!previous)return{kind:'created',source:normalized};if(previous.sourceId!==normalized.sourceId)throw new Error('source identity mismatch');if(previous.contentDigest===normalized.contentDigest&&previous.version===normalized.version)return{kind:'unchanged',source:normalized};return{kind:'changed',source:normalized,previousDigest:previous.contentDigest,changedFields:['version','effectiveAt','content'].filter(k=>previous[k]!==normalized[k])}}
function transition(policy,to,actor){if(!states[policy.status]?.includes(to))throw new Error(`invalid transition ${policy.status} -> ${to}`);const allowed=grants[actor.role]||[];if(!allowed.includes('*')&&!allowed.includes(`${policy.status}:${to}`))throw new Error('role cannot perform transition');if(['approved','released'].includes(to)&&(String(actor.id)===String(policy.ownerId)||String(actor.id)===String(policy.reviewerId)))throw new Error('segregation of duties violation');if(['approval_pending','approved','released'].includes(to)&&!policy.evidenceLinks?.length)throw new Error('evidence links required');return true}
function evaluateScenario(input){const errors=[];if(!input.scenarioId)errors.push('scenario id');if(!input.citations?.length)errors.push('citations');for(const c of input.citations||[])if(!c.sourceUri||!c.sourceVersion||!c.contentDigest)errors.push(`citation:${c.id||'unknown'}`);for(const o of input.obligations||[]){if(!o.ownerId)errors.push(`owner:${o.id}`);if(o.deadlineRequired&&!o.deadline)errors.push(`deadline:${o.id}`);if(!['low','medium','high','critical'].includes(o.riskRating))errors.push(`risk:${o.id}`)}if(!input.obligations?.length)errors.push('obligations');return{passed:errors.length===0,releaseable:errors.length===0,errors,evaluationDigest:digest(input)}}
function retention(record,now=new Date()){if(record.legalHold)return{action:'retain',reason:'legal_hold'};if(!record.retainUntil)return{action:'review',reason:'retention_missing'};return Date.parse(record.retainUntil)<=now.getTime()?{action:'eligible_for_controlled_deletion'}:{action:'retain',reason:'retention_period'}}
function authorize(role,action){const matrix={viewer:['read','export_redacted'],author:['read','create','edit_draft'],reviewer:['read','review'],approver:['read','approve','release'],records_manager:['read','hold','retention','export_audit'],admin:['read','configure_roles']};if(!matrix[role]?.includes(action))throw new Error('forbidden');return true}
module.exports={states,canonical,digest,ingest,detectChange,transition,evaluateScenario,retention,authorize};
